export { default as CheckoutPage } from '__payment__/pages/CheckoutPage'
export { default as MyAccountPage } from '__payment__/pages/MyAccountPage'
export { default as SuccessPage } from '__payment__/pages/SuccessPage'
export { default as PaymentPage } from '__payment__/pages/PaymentPage'
export { default as PaymentRcv } from '__payment__/modules/PaymentRcv'
export { default as PaymentPost } from '__payment__/modules/PaymentPost'
export { default as PaymentAPI } from '__payment__/modules/PaymentAPI'