spring:
    datasource:
        url: jdbc:mariadb://myinstance.co0ymoyz6tmx.ap-northeast-2.rds.amazonaws.com/myinstance
        driverClassName: org.mariadb.jdbc.Driver
        username: myinstance
        password: myinstance

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true

UserController:
    signin: Authenticates user and returns its JWT token.
    signup: Creates user and returns its JWT token
    delete: Deletes specific user by username
    search: Returns specific user by username
    me: Returns current user's data